[package]
name = "borderline"
version = "0.1.0"
edition = "2024"

[dependencies]
core-foundation = "0.10.0"
core-graphics = "0.24.0"
libc = "0.2.172"
objc = "0.2.7"
objc2 = "0.6.1"
accessibility-sys = "0.2"
objc2-app-kit = "0.3.1"
cocoa = "0.26"
